# 应用服务 WEB 访问端口
server:
  port: 48801

spring:
  application:
    name: unif-socket
  datasource:
    #url: jdbc:mysql://124.221.104.154:33801/aiyy_tenant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #username: root
    #password: JKg8pMIz#uDc

    url: jdbc:mysql://10.44.51.172:3307/aiyy_tenant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: H2X2_ttxs

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:mapper/mysql/*.xml
  type-aliases-package: com.example.socketserver.entity

socket:
  schedule: 0 0 0 * * ?
